### PR TITLE
Add specific tests for PurePosixPath and PureWindowsPath

### PR DESCRIPTION
**Pull request by lengau**
#### Describe the changes
Adds tests specific to PurePosixPath and PureWindowsPath to catch issues like #1065 

#### Tasks
- [x] Unit tests added that reproduce the issue or prove feature is working
- [x] Fix or feature added
- [x] Entry to release notes added
- [x] Pre-commit CI shows no errors
- [x] Unit tests passing
- [x] For documentation changes: The Read the Docs preview builds and looks as expected

### CODE REVIEW

**Comment by mrbean-bremen** [comment]
Thanks - I see the failing tests... `is_reserved` has been overwritten for fake `pathlib.Path` (for Python >= 3.12), but obviously not for `Windows/PosixPath`.
I will have a look over the weekend, unless you are going to fix it yourself :)

**Comment by mrbean-bremen** [comment]
@lengau: I added a commit with a fix for the reserved names to this PR (didn't want to copy the tests, or push the fix before the tests). 

I wrote a spin-off issue for the `joinpath` problem under Windows and commented out the failing test for Windows.
I added a workaround for the recursion, so that will not happen anymore, but the test still fails - this turned out to be a bit more complicated.

Please check if that works for you.

**Comment by mrbean-bremen** [comment]
Ok, turned out the `joinpath` problem was easy to fix, I just made a mistake last time I tried it.
I have added an extra commit with the fix.

I'm planning to make a new release with these fixes (and with the official 3.13 support that I also added, as Python 3.13 was released today) soon - please check if this works for you.

**Comment by lengau** [comment]
@mrbean-bremen thanks for doing this! I was meaning to get to it this weekend but ended up being busy with other things. These fixes work for me on my Linux machine.

**Comment by mrbean-bremen** [comment]
> I was meaning to get to it this weekend but ended up being busy with other things

Sounds familiar...

> These fixes work for me on my Linux machine

Ok, I'm going to merge this and make a new release tonight - thanks!

**Pull request merged**
